<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="vishalTest" Id="{36e926be-3fb1-41ad-8761-5d2f09e882c5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK vishalTest
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="vishalTest">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>